name: labhouse
description: "AI-powered Ranking Query App - Labhouse Technical Test"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0

  # Routing
  go_router: ^17.0.1


  # Code Generation
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # HTTP
  dio: ^5.7.0

  # UI
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  google_fonts: ^7.0.0

  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.15
  freezed: ^3.1.0
  json_serializable: ^6.9.4
  riverpod_generator: ^4.0.0+1
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - .env

